### ISSUE TITLE
Gallery items error

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3071]
Check both url:
https://test-data.hdx.rwlabs.org/dataset/wfp-food-prices
and
https://data.hdx.rwlabs.org/dataset/wfp-food-prices

and screenshots
<img width="1280" alt="screen shot 2015-07-13 at 14 02 04" src="https://cloud.githubusercontent.com/assets/3865844/8648262/d3e00ee8-2967-11e5-8917-bc659f363ca2.png">
<img width="1280" alt="screen shot 2015-07-13 at 14 01 58" src="https://cloud.githubusercontent.com/assets/3865844/8648263/d3fafd98-2967-11e5-8a2c-14f4ae0eef07.png">

**Comment by alexandru-m-g** [comment]
@mbellotti as I see here only lite-main.css was changed but not the less file.

**Comment by danmihaila** [comment]
moving it to sprint 66

**Comment by mbellotti** [comment]
lite-main.less doesn't match lite-main.css at all, so how do you want this updated?

**Comment by alexandru-m-g** [comment]
_lite-main.css_ is generated by _lite-main.less_. You just need to follow the trail.

For example: 
- in lite-main.css you have at the end:

``` css
.ie7 .resource-item .btn-group {
  position: relative;
  float: right;
  top: -35px;
  right: 0;
}
```
-  this is generated like this: _lite-main.less -> (imports) ckan.less -> (imports) iehacks.less_ where you can find: 

``` less
.resource-item {
 #...( non-important code )
    .btn-group {
      position: relative;
      float: right;
      top: -35px;
      right: 0;
    }
  }
```
